In [2]:
import numpy as np
A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])
print("Addition:")
print(A + B)
print("Subtraction:")
print(A - B)
print("Multiplication:")
print(A * B)
print("Division:")
print(A / B)
print("Sum of elements in A:")
print(A.sum())


Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape:
(20,)
Maximum value:
20
Minimum value:
1
Mean:
10.5
Standard Deviation:
5.766281297335398
4 x 5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Second Row:
[ 6  7  8  9 10]
Third Column:
[ 3  8 13 18]


In [3]:
import numpy as np
A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])
print("Addition:")
print(A + B)
print("Subtraction:")
print(A - B)
print("Multiplication:")
print(A * B)
print("Division:")
print(A / B)
print("Sum of elements in A:")
print(A.sum())


Addition:
[15 30 45 60 75]
Subtraction:
[ 5 10 15 20 25]
Multiplication:
[  50  200  450  800 1250]
Division:
[2. 2. 2. 2. 2.]
Sum of elements in A:
150


In [2]:
import pandas as pd
data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Ravi", "Priya", "Kiran", "Anu", "Sita"],
    "Marks": [85, 92, 78, 88, 95]
}
df = pd.DataFrame(data)
print("DataFrame")
print(df)
print("\nFirst Three Records")
print(df.head(3))
print("\nAverage Marks")
print(df["Marks"].mean())
print("\nStudent with Highest Marks")
print(df[df["Marks"] == df["Marks"].max()])
print("\nStudent with Lowest Marks")
print(df[df["Marks"] == df["Marks"].min()])
grade = []
for m in df["Marks"]:
    if m >= 90:
        grade.append("A")
    elif m >= 80:
        grade.append("B")
    else:
        grade.append("C")
df["Grade"] = grade
print("\nDataFrame with Grade")
print(df)


DataFrame
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95

First Three Records
   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78

Average Marks
87.6

Student with Highest Marks
   Roll No  Name  Marks
4      105  Sita     95

Student with Lowest Marks
   Roll No   Name  Marks
2      103  Kiran     78

DataFrame with Grade
   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


In [3]:
import pandas as pd
data = [
    ["Laptop", 50000, 10],
    ["Mouse", 500, 50],
    ["Keyboard", 1200, 30],
    ["Monitor", 10000, 15]
]
df = pd.DataFrame(data, columns=["Product", "Price", "Quantity"])
df["Total Value"] = df["Price"] * df["Quantity"]
print("Product Data:")
print(df)
print("\nProduct with Highest Total Value:")
print(df[df["Total Value"] == df["Total Value"].max()])
print("\nOverall Inventory Value:")
print(df["Total Value"].sum())




Product Data:
    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Product with Highest Total Value:
  Product  Price  Quantity  Total Value
0  Laptop  50000        10       500000

Overall Inventory Value:
711000


In [4]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["Target"] = iris.target
print("First Five Records:")
print(df.head())
print("\nNumber of Rows and Columns:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nSummary Statistics:")
print(df.describe())
print("\nNumber of Samples in Each Class:")
print(df["Target"].value_counts())


First Five Records:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0  

Number of Rows and Columns:
(150, 5)

Column Names:
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Target'],
      dtype='str')

Missing Values:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Target               0
dtype: int64

Summary Statistics:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.00000